# Generated by Django 5.1.6 on 2025-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberplatelog',
            old_name='detected_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='numberplatelog',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='numberplatelog',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='numberplatelog',
            name='number_plate',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
