# Generated by Django 5.1.6 on 2025-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_rename_detected_at_numberplatelog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
