# Generated by Django 5.1.6 on 2025-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplatelog',
            name='name',
        ),
        migrations.AddField(
            model_name='numberplatelog',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='numberplatelog',
            name='number_plate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='numberplatelog',
            table='safety_numberplatelog',
        ),
    ]
