# Generated by Django 5.1.6 on 2025-03-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_remove_numberplatelog_name_numberplatelog_owner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warden_name', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
